name: 'Letterboxd Contribution Graph'
description: 'Generate a GitHub-style contribution graph from your Letterboxd watching history'
author: 'nichtlegacy'
inputs:
  letterboxd-username:
    description: 'Your Letterboxd username'
    required: true
  output-path:
    description: 'Path where the SVG file will be saved'
    required: false
    default: 'letterboxd-contribution-graph.svg'
  year:
    description: 'The year to generate the graph for (defaults to current year)'
    required: false
  token:
    description: 'GitHub token for committing the graph'
    required: false
    default: ${{ github.token }}
outputs:
  film-count:
    description: 'Number of films watched in the specified period'
  svg-path:
    description: 'Path to the generated SVG file'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'film'
  color: 'orange'

